# Generated by Django 3.1.3 on 2022-11-01 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_number', models.IntegerField()),
                ('Question', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('option3', models.CharField(max_length=200, null=True)),
                ('option4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=128)),
                ('current_question', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('slot', models.IntegerField(default=0)),
                ('qualified', models.BooleanField(default=False)),
                ('details_updated', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('institute_name', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.CharField(choices=[('Class 9', 'class 9'), ('Class 10', 'class 10'), ('Class 11', 'class 11'), ('Class 12', 'class 12'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('Other', 'Other')], default='1st Year', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
